version: '3.8'
services:
  user-db:
    image: postgres
    restart: always
    container_name: user-db-container
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - "./backend/User Service/pgdata:/var/lib/postgresql/data"

  user-service:
    build: ./backend/User Service
    depends_on:
      - user-db
    container_name: user-service-container
    ports:
      - "4001:4001"
    volumes:
      - "./backend/User Service:/app"
      - "./backend/User Service/node_modules:/app/node_modules"
