version: '3.8'
services:
  user-db:
    image: postgres
    restart: always
    container_name: user-db-container
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - "./backend/User Service/pgdata:/var/lib/postgresql/data"
    env_file:
      - .env

  auth-db:
    image: redis:alpine
    restart: always
    container_name: auth-db-container
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    ports:
      - "6379:6379"
    env_file:
      - .env

  app-db:
    image: mongo
    restart: always
    container_name: app-db-container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - "./backend/App Service/mongodb_data_volume:/data/db"

  api-gateway:
    build: ./backend/Gateway
    container_name: api-gateway-container
    ports:
      - "4000:4000"
    volumes:
      - "./backend/Gateway:/app"
      - "./backend/Gateway/node_modules:/app/node_modules"

  user-service:
    build: ./backend/User Service
    depends_on:
      - user-db
      - api-gateway
    container_name: user-service-container
    ports:
      - "4001:4001"
    volumes:
      - "./backend/User Service:/app"
      - "./backend/User Service/node_modules:/app/node_modules"

  auth-service:
    build: ./backend/Auth Service
    depends_on:
      - auth-db
      - api-gateway
    container_name: auth-service-container
    ports:
      - "4002:4002"
    volumes:
      - "./backend/Auth Service:/app"
      - "./backend/Auth Service/node_modules:/app/node_modules"

  app-service:
    build: ./backend/App Service
    depends_on:
      - app-db
      - api-gateway
    container_name: app-service-container
    ports:
      - "4003:4003"
    volumes:
      - "./backend/App Service:/app"
      - "./backend/App Service/node_modules:/app/node_modules"
